#define MS13_WASTELAND		(1<<0)

#define MS13_WASTELANDER		(1<<0)
#define MS13_CANAANITE		(1<<1)
#define MS13_HUBOLOGIST		(1<<2)

#define MS13_TOWN			(1<<1)

#define MS13_SETTLER		(1<<0)
#define MS13_SQUATTER		(1<<1)
#define MS13_SHOPKEEP		(1<<2)
#define MS13_WORKER			(1<<3)
#define MS13_BARTENDER		(1<<4)
#define MS13_DOCTOR			(1<<5)
#define MS13_DEPUTY			(1<<6)
#define MS13_TOWNBODYGUARD	(1<<7)
#define MS13_SHERIFF		(1<<8)
#define MS13_MAYOR			(1<<9)

#define MS13_NCR				(1<<3)

#define MS13_TROOPER		(1<<0)
#define MS13_MILPOLICE		(1<<1)
#define MS13_RADIOMAN		(1<<2)
#define MS13_ENGINEER		(1<<3)
#define MS13_CORPORAL		(1<<4)
#define MS13_MPMEDIC		(1<<5)
#define MS13_MPSERGEANT 	(1<<6)
#define MS13_SERGEANT		(1<<7)
#define MS13_MEDIC 			(1<<8)
#define MS13_LIEUTENANT		(1<<9)

#define MS13_BOS				(1<<4)

#define MS13_INITIATE		(1<<0)
#define MS13_KNIGHT			(1<<1)
#define MS13_PALADIN		(1<<2)
#define MS13_HEAD_PALADIN	(1<<3)
#define MS13_SCRIBE			(1<<4)
#define MS13_HEAD_SCRIBE	(1<<5)

#define MS13_RAIDERS         (1<<5)

#define MS13_RAIDER			(1<<0)
#define MS13_ENFORCER		(1<<1)
#define MS13_BOSS			(1<<2)
#define MS13_SLICKBACK_COOK	(1<<3)
#define MS13_SLICKBACK		(1<<4)
#define MS13_SLICKBACKUNDERBOSS (1<<5)
#define MS13_MONGRUNT		(1<<6)
#define MS13_MONMARKSMAN	(1<<7)
#define MS13_MONPOINTMAN	(1<<8)
#define MS13_MONCAPT		(1<<9)

// Wasteland
#define JOB_DISPLAY_ORDER_MS13_WASTELANDER 1
#define JOB_DISPLAY_ORDER_MS13_NOMAD 2
#define JOB_DISPLAY_ORDER_MS13_CANAANITE 3
#define JOB_DISPLAY_ORDER_MS13_HUBOLOGIST 4
// Mammoth Town
#define JOB_DISPLAY_ORDER_MS13_SETTLER 5
#define JOB_DISPLAY_ORDER_MS13_SQUATTER 6
#define JOB_DISPLAY_ORDER_MS13_WORKER 7
#define JOB_DISPLAY_ORDER_MS13_BARTENDER 8
#define JOB_DISPLAY_ORDER_MS13_DOCTOR 9
#define JOB_DISPLAY_ORDER_MS13_NURSE 10
#define JOB_DISPLAY_ORDER_MS13_DEPUTY 11
#define JOB_DISPLAY_ORDER_MS13_TOWNBODYGUARD 12
#define JOB_DISPLAY_ORDER_MS13_SHERIFF 13
#define JOB_DISPLAY_ORDER_MS13_MAYOR 14
// NCR
#define JOB_DISPLAY_ORDER_MS13_TROOPER 15
#define JOB_DISPLAY_ORDER_MS13_CORPORAL 16
#define JOB_DISPLAY_ORDER_MS13_RADIOMAN 17
#define JOB_DISPLAY_ORDER_MS13_MEDIC 18
#define JOB_DISPLAY_ORDER_MS13_SERGEANT 19
#define JOB_DISPLAY_ORDER_MS13_LIEUTENANT 20
#define JOB_DISPLAY_ORDER_MS13_NCRRANGER 21
#define JOB_DISPLAY_ORDER_MS13_NCRVETRANGER 22
#define JOB_DISPLAY_ORDER_MS13_QUARTERMASTER 23
#define JOB_DISPLAY_ORDER_MS13_MEDICALOFFICER 24
#define JOB_DISPLAY_ORDER_MS13_REARECHELON 25
// Legion
#define JOB_DISPLAY_ORDER_MS13_RECRUITLEGIONARY 26
#define JOB_DISPLAY_ORDER_MS13_RECRUITDECANUS 27
#define JOB_DISPLAY_ORDER_MS13_PRIMELEGIONARY 28
#define JOB_DISPLAY_ORDER_MS13_PRIMEDECANUS 29
#define JOB_DISPLAY_ORDER_MS13_VETERANLEGIONARY 30
#define JOB_DISPLAY_ORDER_MS13_VETERANDECANUS 31
#define JOB_DISPLAY_ORDER_MS13_CENTURION 32
#define JOB_DISPLAY_ORDER_MS13_EXPLORER 33
#define JOB_DISPLAY_ORDER_MS13_LEGIONSMITH 34
#define JOB_DISPLAY_ORDER_MS13_LEGIONMEDICUS 35
#define JOB_DISPLAY_ORDER_MS13_LEGIONCAMPAUXILIA 36
// Brotherhood of Steel
#define JOB_DISPLAY_ORDER_MS13_INITIATE 37
#define JOB_DISPLAY_ORDER_MS13_KNIGHT 38
#define JOB_DISPLAY_ORDER_MS13_HEAD_PALADIN 39
#define JOB_DISPLAY_ORDER_MS13_SCRIBE 40
#define JOB_DISPLAY_ORDER_MS13_HEAD_SCRIBE 41
#define JOB_DISPLAY_ORDER_MS13_BASE_STAFF 42
// Drought Raider
#define JOB_DISPLAY_ORDER_MS13_RAIDER 43
#define JOB_DISPLAY_ORDER_MS13_SAWBONE 44
#define JOB_DISPLAY_ORDER_MS13_ENFORCER 45
#define JOB_DISPLAY_ORDER_MS13_BOSS 46
// Desert Rangers
#define JOB_DISPLAY_ORDER_MS13_RANGERDOCTOR 47
#define JOB_DISPLAY_ORDER_MS13_RANGERSHARP 48
#define JOB_DISPLAY_ORDER_MS13_RANGER 49
#define JOB_DISPLAY_ORDER_MS13_RANGERELITE 50
#define JOB_DISPLAY_ORDER_MS13_RANGERDEPUTYCHIEF 51
// Combat test
#define JOB_DISPLAY_ORDER_MS13_BLUE 52
#define JOB_DISPLAY_ORDER_MS13_RED 53
// Drought Town
#define JOB_DISPLAY_ORDER_MS13_CARLINDENIZEN 55
#define JOB_DISPLAY_ORDER_MS13_CARLINLABORER 56
#define JOB_DISPLAY_ORDER_MS13_CARLINBARKEEP 57
#define JOB_DISPLAY_ORDER_MS13_CARLINSHOPKEEP 58
#define JOB_DISPLAY_ORDER_MS13_CARLINCLINICIAN 59
#define JOB_DISPLAY_ORDER_MS13_CARLINENFORCER 60
#define JOB_DISPLAY_ORDER_MS13_CARLINSHERIFF 61
#define JOB_DISPLAY_ORDER_MS13_CARLINMAYOR 62
// Drylander Tribe
#define JOB_DISPLAY_ORDER_MS13_DRYFOLK 63
#define JOB_DISPLAY_ORDER_MS13_HUNTER 64
#define JOB_DISPLAY_ORDER_MS13_HEADTAKER 65
#define JOB_DISPLAY_ORDER_MS13_SHAMAN 66
#define JOB_DISPLAY_ORDER_MS13_CHIEFTAIN 67
// Mammoth Raider
#define JOB_DISPLAY_ORDER_MS13_SLICKBACKCOOK 68
#define JOB_DISPLAY_ORDER_MS13_SLICKBACK 69
#define JOB_DISPLAY_ORDER_MS13_SLICKUNDERBOSS 70
#define JOB_DISPLAY_ORDER_MS13_MONGRUNT 71
#define JOB_DISPLAY_ORDER_MS13_MONMARKSMAN 72
#define JOB_DISPLAY_ORDER_MS13_MONPOINTMAN 73
#define JOB_DISPLAY_ORDER_MS13_MONCAPT 74
// Goldman Posse
#define JOB_DISPLAY_ORDER_MS13_GLDMNUNPROVEN 75
#define JOB_DISPLAY_ORDER_MS13_GOLDMAN 76
#define JOB_DISPLAY_ORDER_MS13_GLDMNROADRUN 77
#define JOB_DISPLAY_ORDER_MS13_GLDMNKEEPER 78
#define JOB_DISPLAY_ORDER_MS13_GLDMNOVER 79


#define EXP_TYPE_WASTELAND "Wasteland"
#define EXP_TYPE_TOWN "Town"
#define EXP_TYPE_LEGION "Legion"
#define EXP_TYPE_NCR "NCR"
#define EXP_TYPE_BOS "BOS"
#define EXP_TYPE_RAIDERS "Raiders"
#define EXP_TYPE_RANGERS "Rangers"
#define EXP_TYPE_DROUGHTTOWN "Town"
#define EXP_TYPE_DRYLANDERS "Drylanders"
#define EXP_TYPE_COMBATTEST "Combattest"
#define EXP_TYPE_GOLDMAN "Goldman Posse"
